# Generated by Django 4.1.5 on 2023-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo_url", models.URLField()),
                ("address", models.CharField(max_length=100)),
                ("open", models.CharField(max_length=400)),
                ("close", models.CharField(max_length=400)),
                ("catch", models.CharField(max_length=100)),
                ("access", models.CharField(max_length=400)),
                ("genre_name", models.CharField(max_length=100)),
                ("genre_catch", models.CharField(max_length=100)),
                ("parking", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
