# Generated by Django 4.1.5 on 2023-01-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("near_search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="access",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="catch",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="close",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="genre_catch",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="genre_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="open",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="parking",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="photo_url",
            field=models.URLField(null=True),
        ),
    ]
