# Generated by Django 4.1.5 on 2023-01-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("near_search", "0002_alter_shop_access_alter_shop_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
